name: dragscheduler
description: dragscheduler.
version: 0.9.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0-dev.11
  flutter_native_splash: ^1.2.4

flutter:
  uses-material-design: true

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  color: "000000"
  image: "lib/assets/splash.png"