name: contentscheduler
description: contentscheduler
version: 0.9.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0-dev.11
  flutter_native_splash: ^1.2.4
  fl_chart: ^0.36.1
  flutter_svg: ^0.22.0
  data_table_2: ^2.0.3  
  google_fonts: ^2.1.0

flutter:
  uses-material-design: true

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  color: "000000"
  image: "lib/assets/splash.png"